graph:
  edge_default: {}
  graph_default:
    history: List
    topic: Text
    topic_lst: Text
    topic_trick: Text
    worries_lst: Text
  node_default:
    field: None
    next: None
    template: None
    utter: None
links:
- source: entry
  target: ask_judge
- source: entry
  target: exit
- source: ask_conclude
  target: think
- source: think
  target: talk
nodes:
- id: n0
  label: entry
  shape_type: rectangle
  template: "entry prompt]></data>\n      <data key=\"d11\" xml:space=\"preserve\"\
    ><![CDATA[[{\"if\": \"{'1'} contains output\", \"then\": \"ask_judge\"}, {\"else\"\
    : \"exit\"}]"
  x: '4.3154296875'
  y: '-118.0'
- field: guess
  id: n1
  label: ask_judge
  next:
  - if: '{''信息不足''} contains output'
    then: ask_guess
  - else: ask_conclude
  shape_type: rectangle
  template: ask_judge prompt
  x: '-45.6845703125'
  y: '-46.0'
- field: concern
  id: n2
  label: ask_conclude
  shape_type: rectangle
  template: ask_conclude prompt
  x: '4.3154296875'
  y: '43.0'
- field: strategy
  id: n3
  label: think
  shape_type: rectangle
  template: think prompt
  x: '4.3154296875'
  y: '117.0'
- id: n4
  label: talk
  shape_type: rectangle
  template: talk prompt
  x: '4.3154296875'
  y: '191.0'
- id: n5
  label: ask_guess
  shape_type: rectangle
  template: ask_guess prompt
  x: '-82.369140625'
  y: '191.0'
- id: n6
  label: exit
  shape_type: rectangle
  utter: not in this_topic
  x: '91.0'
  y: '191.0'
